    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              name: Checkout project
            - uses: actions/setup-java@v3
              name: Setup Java
              with: 
                distribution: 'temurin'
                java-version: 17
            - name: Run Tests and Build
              run: ./mvnw clean test compile war:war
