name: Build and Test
run-name: Build and Test
on:
    push:
      branches: [ develop ]
      tags: [ build ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

              name: Checkout project
            - uses: actions/setup-java@v3
              name: Setup Java
              with: 
                distribution: 'temurin'
                java-version: 17


            - name: Grant execute permission for gradlew
              run: chmod +x gradlew

            - name: Build with Gradle
              run: ./gradlew clean build

            - name: Build the Docker image
              run: docker build . --file Dockerfile
 
